
CREATE TABLE login_log
(
	time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ip VARCHAR(15) NOT NULL DEFAULT '127.0.0.1',
	username VARCHAR(24) NOT NULL,
	rcode TINYINT NOT NULL,
	message VARCHAR(255)
) ENGINE=MyISAM;
