
DROP TABLE logins;

ALTER TABLE accounts DROP PRIMARY KEY;
ALTER TABLE accounts DROP COLUMN login;
ALTER TABLE accounts ADD PRIMARY KEY (id), ADD COLUMN id INT AUTO_INCREMENT FIRST, AUTO_INCREMENT=1000001;
ALTER TABLE accounts ADD COLUMN username VARCHAR(23) NOT NULL AFTER id;
ALTER TABLE accounts ADD COLUMN password VARCHAR(32) NOT NULL AFTER username;
ALTER TABLE accounts ADD COLUMN last_login DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER password;
ALTER TABLE accounts ADD COLUMN registered DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER last_login;

ALTER TABLE accounts_groups ADD FOREIGN KEY (current_group) REFERENCES groups (id);
ALTER TABLE accounts_groups ADD FOREIGN KEY (old_group) REFERENCES groups (id);
ALTER TABLE accounts_groups ADD FOREIGN KEY (vip) REFERENCES vip (id);
